export const APP_NAME = 'Kally Threading – Multi-Branch CRM';

/** Logo used on login and in app nav (sidebar/topbar). File: public/images/Kally-Logo (1).webp */
export const LOGO_URL = '/images/Kally-Logo%20(1).webp';

export const ROUTES = {
  login: '/login',
  forgotPassword: '/forgot-password',
  admin: {
    root: '/admin',
    overview: '/admin/overview',
    vendors: '/admin/vendors',
    createVendor: '/admin/create-vendor',
    branches: '/admin/branches',
    sales: '/admin/sales',
    salesImages: '/admin/sales-images',
    memberships: '/admin/memberships',
    membershipsNewCustomer: '/admin/memberships/new-customer',
    membershipDetail: (id: string) => `/admin/memberships/${id}`,
    customers: '/admin/customers',
    customerMemberships: (customerId: string) => `/admin/customers/${customerId}/memberships`,
    customerAppointments: (customerId: string) => `/admin/customers/${customerId}/appointments`,
    packages: '/admin/packages',
    search: '/admin/search',
    leads: '/admin/leads',
    leadDetail: (id: string) => `/admin/leads/${id}`,
    appointments: '/admin/appointments',
    services: '/admin/services',
    settlements: '/admin/settlements',
    loyalty: '/admin/loyalty',
    loyaltyDetail: (customerId: string) => `/admin/loyalty/${customerId}`,
    guidelines: '/admin/guidelines',
    settings: '/admin/settings',
    rolesPermissions: '/admin/roles-permissions',
    profile: '/admin/profile',
    tickets: '/admin/tickets',
    ticketDetail: (id: string) => `/admin/tickets/${id}`,
    activityLog: '/admin/activity-log',
  },
  vendor: {
    root: '/vendor',
    branches: '/vendor/branches',
    sales: '/vendor/sales',
    salesImages: '/vendor/sales-images',
    memberships: '/vendor/memberships',
    membershipsNewCustomer: '/vendor/memberships/new-customer',
    membershipDetail: (id: string) => `/vendor/memberships/${id}`,
    customers: '/vendor/customers',
    customerMemberships: (customerId: string) => `/vendor/customers/${customerId}/memberships`,
    packages: '/vendor/packages',
    customerAppointments: (customerId: string) => `/vendor/customers/${customerId}/appointments`,
    search: '/vendor/search',
    leads: '/vendor/leads',
    leadDetail: (id: string) => `/vendor/leads/${id}`,
    appointments: '/vendor/appointments',
    services: '/vendor/services',
    settlements: '/vendor/settlements',
    loyalty: '/vendor/loyalty',
    loyaltyDetail: (customerId: string) => `/vendor/loyalty/${customerId}`,
    guidelines: '/vendor/guidelines',
    profile: '/vendor/profile',
    tickets: '/vendor/tickets',
    ticketDetail: (id: string) => `/vendor/tickets/${id}`,
    activityLog: '/vendor/activity-log',
  },
} as const;
